### ISSUE TITLE
(Not a issue) Finished PartnerXBoxInput.java

### ISSUE THREAD

**Issue by XRuizhe** [2585Robophiles/FRC2015#19]
finished partnerXBoxInput for the FRC2015 i forked,
check it plox

(don't have gitbash, can't request)

**Comment by LoadingPleaseWait** [comment]
Just make a pull request. https://help.github.com/articles/creating-a-pull-request/

**Comment by XRuizhe** [comment]
don't have gitbash atm (where's the download?)

**Comment by LoadingPleaseWait** [comment]
You don't need git bash to make a pull request. Look at https://help.github.com/articles/creating-a-pull-request/ for making a pull request in your browser. I only use my web browser for working with pull requests. Also, you can download git bash at http://git-scm.com for all major platforms.
